### ISSUE TITLE
How to use cargo-vcpkg inside library project

### ISSUE THREAD

**Issue by CGQAQ** [mcgoo/cargo-vcpkg#18]
<img width="1010" alt="image" src="https://user-images.githubusercontent.com/15936231/232309785-0d9397a6-f611-41fd-963c-38faa34bba8f.png">

Put `cargo vckpg build` inside build script will cause:

```
error: failed to verify package tarball

Caused by:
  Source directory was modified by build.rs during cargo publish. Build scripts should not modify anything outside of OUT_DIR.
  Added: C:\repo\harfbuzz-bindings\target\package\harfbuzz-bindings-0.2.0\Cargo.lock
```

then how do I suppose to use cargo-vcpkg inside library project

**Comment by pkgw** [comment]
Hi,

Apologies that it has taken so long to reply to this issue. As a general rule, I would strongly recommend against running any `cargo` commands as subcommands in your `build.rs`, since at a minimum they are likely to trigger the sort of warning you are seeing, and they will potentially cause problems for `cargo`'s state management. I'm not aware of a specific failure that I'd expect such a setup to cause, but it is very much not the intended usage of any of these tools.

Instead, I would recommend that commands like `cargo install ...` or `cargo vcpkg ...` be part of your standard build instructions, but not integrated into `build.rs`. These commands should generally be run a lot more rarely than `cargo build`, so it makes sense to keep them separate.

I'm going to close this issue because it is very old and because I don't think it indicates anything about `cargo-vcpkg` that needs to be changed, but we can keep on commenting if you have any further questions.
