### ISSUE TITLE
cargo vcpkg build command errors out

### ISSUE THREAD

**Issue by mario-hess** [mcgoo/cargo-vcpkg#21]
I followed the instructions and installed cargo-vcpkg. As soon as I run cargo vcpkg build it errors out:
```
Fetching vcpkg
-- stdout --

-- stderr --
fatal: not a git repository (or any of the parent directories): .git

cargo-vcpkg: failed to run git fetch

```
I am in my root project folder which is a git repo and I followed every step.
What am I doing wrong?

**Comment by mario-hess** [comment]
close

**Comment by DavidTruby** [comment]
Hi, did you resolve this? I have the same issue

**Comment by akiross** [comment]
I stumbled in something similar, the issue was that I had a system installation of vcpkg, so `VCPKG_ROOT` was set and it would attempt to fetch from that root - which is not a git repo. I resolved this issue by specifying a different `VCPKG_ROOT` for my project, like `VCPKG_ROOT=target/vcpkg cargo vcpkg -v build`
